name: CI/CD

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  jobs:
    run-tests:
    name: Setup python
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13

    jobs:
      run-tests:
      name: Setup python
      runs-on: windows-latest

      steps:
        - name: Install dependencies
          run: python -m pip install -r requirements.txt

      jobs:
        run-tests:
        name: Run demo
        runs-on: windows-latest

        steps:
          - name: Run tests
            run: pytest