name: CI/CD

on:
  push:
  pull_request:

jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  job2:
    name: Setup python
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13

  job3:
    name: Install deps
    needs: job2
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: python -m pip install -r ./pytest-selenium/requirements.txt

  job4:
    name: Run Demo
    needs: job3
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: pytest