name: CI/CD

on:
  push:
  pull_request:

jobs:
  job1:
    run-tests:
      name: Test
      runs-on: windows-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  job2:
    - steps:
        - name: Set up Python
          uses: actions/checkout@v4
          with:
            python-version: 3.13
  job3:
    - steps:
        - name: Install dependencies
          run: python -m pip install -r requirements.txt
  job4:
    - steps:
        - name: Run tests
          run: pytest